[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "weather_app"
version = "1.0.0"
dependencies = [
    "requests",
    "click",
]

[tool.setuptools.packages.find]
include = ["weather_app*"]

[tool.ruff.format]
quote-style = "single"
